from Solution import *
from Business.Disk import Disk


print("starting")
# #print(getFiles())
dropTables()
file1 = File(2, "HOMO", 10)
file2 = File(3, "HOMO1", 1)
ram1 = RAM(10, 'a', 20)
ram2 = RAM(11, 'a', 20)
disk1 = Disk(1, 'a', 2, 15, 4)
disk2 = Disk(2, 'a', 2, 17, 4)
disk3 = Disk(3, 'a', 2, 18, 4)
createTables()
addFile(file1)
addFile(file2)
addDisk(disk1)
addDisk(disk2)
addDisk(disk3)
addRAM(ram1)
addRAM(ram2)
#print(getFiles())
addFileToDisk(file1, 1)
addFileToDisk(file2, 1)
addFileToDisk(file1, 2)
addFileToDisk(file2, 3)
print(addRAMToDisk(ram1.getRamID(), disk1.getDiskID()))
print(addRAMToDisk(ram2.getRamID(), disk1.getDiskID()))
#print(getFilesCanBeAddedToDisk(disk.getDiskID()))
#print(getFilesCanBeAddedToDiskAndRAM(disk.getDiskID()))
# print(isCompanyExclusive(disk1.getDiskID()))
print(getConflictingDisks())
print(mostAvailableDisks())
